CREATE TABLE item (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  description VARCHAR(2000),
  price_cents BIGINT NOT NULL,
  status VARCHAR(16) NOT NULL,
  seller_id BIGINT NOT NULL,
  version BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
